const actionTypes = {
    FETCH_SUCCESS: 'FETCH_SUCCESS',
    FETCH_ERROR: 'FETCH_ERROR',
    SET_PAGE: 'SET_PAGE',
    SET_LOADING: 'SET_LOADING',
    SET_USER: 'SET_USER',
    OPEN_MESSAGE_TOAST: 'OPEN_MESSAGE_TOAST',
    CLOSE_MESSAGE_TOAST: 'CLOSE_MESSAGE_TOAST',
    SET_CURRENT_IMAGE: 'SET_CURRENT_IMAGE',
    SEARCH_PHOTOS: 'SEARCH_PHOTOS',
    SET_PHOTO_STATISTICS:'SET_PHOTO_STATISTICS',
    SET_DARK_THEME: 'SET_DARK_THEME',
    SET_LIGHT_THEME: 'SET_LIGHT_THEME',
}

export default actionTypes
