const actionTypes = {
    FETCH_SUCCESS: 'FETCH_SUCCESS',
    FETCH_ERROR: 'FETCH_ERROR',
    SET_PAGE: 'SET_PAGE',
    SET_LOADING: 'SET_LOADING',
    SET_USER: 'SET_USER',
    OPEN_MESSAGE_TOAST: 'OPEN_MESSAGE_TOAST',
    CLOSE_MESSAGE_TOAST: 'CLOSE_MESSAGE_TOAST',
}

export default actionTypes
